trigger:
- master
- push-refresh
- v1-preview

pr:
- master
- push-refresh
- v1-preview

pool:
  name: Hosted Mac Internal
  demands: java

steps:
- task: Gradle@2
  displayName: 'Execute SDK (non-emulator) Tests'
  inputs:
    options: '-p notification-hubs-sdk'
    tasks: 'cleanTest test'

- task: DownloadSecureFile@1
  displayName: 'Download Google Services profile'
  name: googleServices
  inputs:
    secureFile: google-services.json

- task: Bash@3
  displayName: 'Copy Google Service profile to application roots'
  inputs:
    targetType: 'inline'
    script: |
      cp $(googleServices.secureFilePath) ./notification-hubs-test-app-legacy
      cp $(googleServices.secureFilePath) ./notification-hubs-test-app-java

- task: Gradle@2
  displayName: 'Build and test sample app'
  inputs:
    options: '-PisCI="true"'
    tasks: 'notification-hubs-test-app-java:test notification-hubs-test-app-java:connectedAndroidTest'
    publishJUnitResults: false

- task: Gradle@2
  displayName: 'Create assets for publication'
  inputs:
    options: '-PisCI="true"'
    tasks: 'makeJar notification-hubs-sdk:publishReleasePublicationToBuildDirRepository notification-hubs-sdk:writeVersionFile'
    publishJUnitResults: false


- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSigning'
  inputs:
    ConnectedServiceName: 'ESRP CodeSigning'
    FolderPath: '$(build.artifactstagingdirectory)/com/microsoft/azure'
    Pattern: '*.jar, *.aar'
    signConfigType: inlineSignParams
    inlineOperation: |
     [
         {
             "keyCode": "CP-447347-Java",
             "operationSetCode": "JavaSign",
             "parameters": [
                 {
                     "parameterName": "SigAlg",
                     "parameterValue": "SHA256withRSA"
                 },
                 {
                     "parameterName": "TimeStamp",
                     "parameterValue": "-tsa \"http://sha256timestamp.ws.symantec.com/sha256/timestamp\""
                 }
             ],
             "toolName": "Jarsigner.exe",
             "toolVersion": "V1.8.112"
         },
         {
             "keyCode": "CP-447347-Java",
             "operationSetCode": "JavaVerify",
             "parameters": null,
             "toolName": "Jarsigner.exe",
             "toolVersion": "V1.8.112"
         }
     ]
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: /
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
